import type { Metadata } from "next";
import { soehneBreit } from "./fonts/index";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={soehneBreit.variable}>
      <body
        className="font-soehne"
      >
        {children}
      </body>
    </html>
  );
}
